# Generated by Django 2.0.3 on 2018-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('date', models.DateTimeField(verbose_name='дата запроса')),
                ('method', models.TextField(blank=True, default='', max_length=25, verbose_name='HTTP - метод')),
                ('url', models.URLField(default='', verbose_name='URL')),
                ('id_resp', models.IntegerField(blank=True, default=0, verbose_name='код ответа')),
                ('resp_size', models.IntegerField(blank=True, default=0, verbose_name='размер ответа')),
            ],
        ),
    ]
