# Generated by Django 2.0.3 on 2018-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_log', '0003_auto_20180325_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='id_resp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='resp_size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
