# Generated by Django 2.0.3 on 2018-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_log', '0004_auto_20180326_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='дата запроса'),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='id_resp',
            field=models.IntegerField(blank=True, default=0, verbose_name='код ответа'),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='method',
            field=models.TextField(blank=True, default='', max_length=25, verbose_name='HTTP - метод'),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='resp_size',
            field=models.IntegerField(blank=True, default=0, verbose_name='размер ответа'),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='url',
            field=models.UUIDField(default='', verbose_name='URL'),
        ),
    ]
