# Generated by Django 2.0.3 on 2018-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_log', '0005_auto_20180327_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
        ),
    ]
